
server:
  port: 12345

spring:
  application:
    name: spring-example-test

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
#  redis:
#    host: localhost # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    timeout: 1000ms # 连接超时时间
  profiles:
    active: dev
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  apple:
    price: 3
    size: "big"

com:
  junyi:
    id: 13
    name: fruit
